### ISSUE TITLE
Issue in using Standalone En2Indic Model

### ISSUE THREAD

**Issue by kranti-experiments** [AI4Bharat/indicTrans#18]
Hi,
If I download the En2Indic Model and try to use it, I am getting the following error:
```bash
ModuleNotFoundError: No module named 'inference'
```

However, if I first download Indic2En Model and then download EN2Indic model things are working fine. Can you please check if it is the same behaviour for you also? or Am I doing something wrong?

Colab Links for your reference:

Working only after Indic2En model
https://colab.research.google.com/drive/1HxG1_lvZ7XDD89QbVikajg0HJnQvNrgR?usp=sharing

Not Working if EN2Indic model is downloaded
https://colab.research.google.com/drive/1QAQg0557YVgoPLfC7MMtbnfHNNmFpu-m?usp=sharing

**Comment by gowtham1997** [comment]
The problem is you are not in `indicTrans` folder when importing the inference module and that causes the error.

![image](https://user-images.githubusercontent.com/9641196/129477699-61c668f1-d5f8-4023-b418-c921591a38c5.png)

^ adding `cd indicTrans` before your import in the second colab fixes the problem.


The error occurs as you are restarting the runtime after installing fairseq but not in indicTrans folder before running the `from indicTrans.inference.engine import Model` import.

**Comment by kranti-experiments** [comment]
oh ok, I did add cd indicTrans but after that I have restarted the runtime. I will try again.
Thank you
