### ISSUE TITLE
Chunks lost in translation

### ISSUE THREAD

**Issue by PS-AI** [AI4Bharat/indicTrans#25]
Hi,
Thank you for your work on indicTrans. I have been using this to translate some short paragraphs( 3-4 sentences) in various supported Indic languages.  I noticed that there is a certain amount of data that gets lost in translation. For example- I am trying to translate this English sentence to Tamil:
"In order to make the French capital safer, quieter and less dirty,a speed limit of 30 kmph for cars came into force in Paris on Monday"
This is translated as:
பிரான்ஸ் தலைநகர் பாரிஸில் கார்களுக்கு மணிக்கு 30 கிலோமீட்டர் வேகத்தில் செல்லலாம் என்ற கட்டுப்பாடு விதிக்கப்பட்டுள்ளது

The chunk- "In order to make the French capital safer, quieter and less dirty" is lost in the translation

I assumed that with the Transformer architecture, long sentences too could be translated more accurately.

I would like to know what could be done to fix this issue.

**Comment by PS-AI** [comment]
@gowtham1997  Thank you for your response. I am using the python interface. The paragraph is split into lines before attempting translation.

The Samanantar paper mentions - "sentence pairs with longer sentences are unlikely to have high alignment on LaBSE representations and thus be included in Samanantar"

Could this be an issue due to the data that IndicTrans was trained on( i.e no such long sentences in the training data) ?

**Comment by gowtham1997** [comment]
I am not sure about the cause @PS-AI .

But we have now released newer version of the translation models (V0.3) and it seems to preserve the whole sentence during translation.

"In order to make the French capital safer, quieter, and less dirtier, a speed limit of 30 kmph for cars came into force in Paris on Monday" 
translates to

"பிரான்ஸ் தலைநகரை பாதுகாப்பானதாகவும், அமைதியானதாகவும், தூய்மையற்றதாகவும் மாற்றுவதற்காக, கார்களுக்கான வேக வரம்பு மணிக்கு 30 கி. மீ. என பாரீஸ் நகரில் திங்கள்கிழமை முதல் அமலுக்கு வந்துள்ளது."

^ Note that I have changed "less dirty" to "less dirtier" (cleaner also works). For some reason, the model gives "அழுக்கானதாகவும்" for "less dirty", so it still needs some improvement.

**Comment by gowtham1997** [comment]
![image](https://user-images.githubusercontent.com/9641196/146734206-bd0c7045-6843-4617-bc41-90fd81c39d54.png)
Even google translate seems to make the same mistake for En to Tamil which is surprising. 

Thanks for bringing this to our notice. If you find similar sentences where translations quality is bad, please feel free to let us know
